export const strings = {
  // forDrivers: 'For Drivers',
  welcome: 'Welcome',
  signIn: 'Sign in and get started',
  phone: 'Phone',
  password: 'Password',
  login: 'LOGIN',
  forgetPassword: 'Forgot password?',
  dontHaveAccount: 'Don’t have an account?',
  signUp: ' Signup',
  pleaseSelect: 'Please select before\ncontinuing to Signup',
  continueAsInstructor: 'Continue as a\ninstructor/driving\nschool',
  continueAsStudent: 'Continue as\na Student',
  goBack: 'Go Back',
};
